//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumidor.Sref {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sref.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Consumidor.Sref.HelloWorldResponse HelloWorld(Consumidor.Sref.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Sref.HelloWorldResponse> HelloWorldAsync(Consumidor.Sref.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cod del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_prod", ReplyAction="*")]
        Consumidor.Sref.insert_prodResponse insert_prod(Consumidor.Sref.insert_prodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_prod", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Sref.insert_prodResponse> insert_prodAsync(Consumidor.Sref.insert_prodRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento get_prodResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_prod", ReplyAction="*")]
        Consumidor.Sref.get_prodResponse get_prod(Consumidor.Sref.get_prodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_prod", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Sref.get_prodResponse> get_prodAsync(Consumidor.Sref.get_prodRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento get_all_prodResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_all_prod", ReplyAction="*")]
        Consumidor.Sref.get_all_prodResponse get_all_prod(Consumidor.Sref.get_all_prodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_all_prod", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Sref.get_all_prodResponse> get_all_prodAsync(Consumidor.Sref.get_all_prodRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cod del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_prod", ReplyAction="*")]
        Consumidor.Sref.update_prodResponse update_prod(Consumidor.Sref.update_prodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_prod", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Sref.update_prodResponse> update_prodAsync(Consumidor.Sref.update_prodRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento delete_prodResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_prod", ReplyAction="*")]
        Consumidor.Sref.delete_prodResponse delete_prod(Consumidor.Sref.delete_prodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_prod", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Sref.delete_prodResponse> delete_prodAsync(Consumidor.Sref.delete_prodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Consumidor.Sref.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Consumidor.Sref.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_prodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_prod", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.insert_prodRequestBody Body;
        
        public insert_prodRequest() {
        }
        
        public insert_prodRequest(Consumidor.Sref.insert_prodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_prodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string desc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double compra;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double venta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string material;
        
        public insert_prodRequestBody() {
        }
        
        public insert_prodRequestBody(string cod, string nombre, string marca, string desc, double compra, double venta, string material) {
            this.cod = cod;
            this.nombre = nombre;
            this.marca = marca;
            this.desc = desc;
            this.compra = compra;
            this.venta = venta;
            this.material = material;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_prodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_prodResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.insert_prodResponseBody Body;
        
        public insert_prodResponse() {
        }
        
        public insert_prodResponse(Consumidor.Sref.insert_prodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_prodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insert_prodResult;
        
        public insert_prodResponseBody() {
        }
        
        public insert_prodResponseBody(string insert_prodResult) {
            this.insert_prodResult = insert_prodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_prodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_prod", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.get_prodRequestBody Body;
        
        public get_prodRequest() {
        }
        
        public get_prodRequest(Consumidor.Sref.get_prodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_prodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public get_prodRequestBody() {
        }
        
        public get_prodRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_prodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_prodResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.get_prodResponseBody Body;
        
        public get_prodResponse() {
        }
        
        public get_prodResponse(Consumidor.Sref.get_prodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_prodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string get_prodResult;
        
        public get_prodResponseBody() {
        }
        
        public get_prodResponseBody(string get_prodResult) {
            this.get_prodResult = get_prodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_all_prodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_all_prod", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.get_all_prodRequestBody Body;
        
        public get_all_prodRequest() {
        }
        
        public get_all_prodRequest(Consumidor.Sref.get_all_prodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class get_all_prodRequestBody {
        
        public get_all_prodRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_all_prodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_all_prodResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.get_all_prodResponseBody Body;
        
        public get_all_prodResponse() {
        }
        
        public get_all_prodResponse(Consumidor.Sref.get_all_prodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_all_prodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string get_all_prodResult;
        
        public get_all_prodResponseBody() {
        }
        
        public get_all_prodResponseBody(string get_all_prodResult) {
            this.get_all_prodResult = get_all_prodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class update_prodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update_prod", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.update_prodRequestBody Body;
        
        public update_prodRequest() {
        }
        
        public update_prodRequest(Consumidor.Sref.update_prodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class update_prodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string desc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double compra;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double venta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string material;
        
        public update_prodRequestBody() {
        }
        
        public update_prodRequestBody(int id, string cod, string nombre, string marca, string desc, double compra, double venta, string material) {
            this.id = id;
            this.cod = cod;
            this.nombre = nombre;
            this.marca = marca;
            this.desc = desc;
            this.compra = compra;
            this.venta = venta;
            this.material = material;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class update_prodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update_prodResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.update_prodResponseBody Body;
        
        public update_prodResponse() {
        }
        
        public update_prodResponse(Consumidor.Sref.update_prodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class update_prodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string update_prodResult;
        
        public update_prodResponseBody() {
        }
        
        public update_prodResponseBody(string update_prodResult) {
            this.update_prodResult = update_prodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_prodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_prod", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.delete_prodRequestBody Body;
        
        public delete_prodRequest() {
        }
        
        public delete_prodRequest(Consumidor.Sref.delete_prodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class delete_prodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public delete_prodRequestBody() {
        }
        
        public delete_prodRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_prodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_prodResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumidor.Sref.delete_prodResponseBody Body;
        
        public delete_prodResponse() {
        }
        
        public delete_prodResponse(Consumidor.Sref.delete_prodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class delete_prodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string delete_prodResult;
        
        public delete_prodResponseBody() {
        }
        
        public delete_prodResponseBody(string delete_prodResult) {
            this.delete_prodResult = delete_prodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Consumidor.Sref.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Consumidor.Sref.WebService1Soap>, Consumidor.Sref.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Sref.HelloWorldResponse Consumidor.Sref.WebService1Soap.HelloWorld(Consumidor.Sref.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Consumidor.Sref.HelloWorldRequest inValue = new Consumidor.Sref.HelloWorldRequest();
            inValue.Body = new Consumidor.Sref.HelloWorldRequestBody();
            Consumidor.Sref.HelloWorldResponse retVal = ((Consumidor.Sref.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Sref.HelloWorldResponse> Consumidor.Sref.WebService1Soap.HelloWorldAsync(Consumidor.Sref.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Sref.HelloWorldResponse> HelloWorldAsync() {
            Consumidor.Sref.HelloWorldRequest inValue = new Consumidor.Sref.HelloWorldRequest();
            inValue.Body = new Consumidor.Sref.HelloWorldRequestBody();
            return ((Consumidor.Sref.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Sref.insert_prodResponse Consumidor.Sref.WebService1Soap.insert_prod(Consumidor.Sref.insert_prodRequest request) {
            return base.Channel.insert_prod(request);
        }
        
        public string insert_prod(string cod, string nombre, string marca, string desc, double compra, double venta, string material) {
            Consumidor.Sref.insert_prodRequest inValue = new Consumidor.Sref.insert_prodRequest();
            inValue.Body = new Consumidor.Sref.insert_prodRequestBody();
            inValue.Body.cod = cod;
            inValue.Body.nombre = nombre;
            inValue.Body.marca = marca;
            inValue.Body.desc = desc;
            inValue.Body.compra = compra;
            inValue.Body.venta = venta;
            inValue.Body.material = material;
            Consumidor.Sref.insert_prodResponse retVal = ((Consumidor.Sref.WebService1Soap)(this)).insert_prod(inValue);
            return retVal.Body.insert_prodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Sref.insert_prodResponse> Consumidor.Sref.WebService1Soap.insert_prodAsync(Consumidor.Sref.insert_prodRequest request) {
            return base.Channel.insert_prodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Sref.insert_prodResponse> insert_prodAsync(string cod, string nombre, string marca, string desc, double compra, double venta, string material) {
            Consumidor.Sref.insert_prodRequest inValue = new Consumidor.Sref.insert_prodRequest();
            inValue.Body = new Consumidor.Sref.insert_prodRequestBody();
            inValue.Body.cod = cod;
            inValue.Body.nombre = nombre;
            inValue.Body.marca = marca;
            inValue.Body.desc = desc;
            inValue.Body.compra = compra;
            inValue.Body.venta = venta;
            inValue.Body.material = material;
            return ((Consumidor.Sref.WebService1Soap)(this)).insert_prodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Sref.get_prodResponse Consumidor.Sref.WebService1Soap.get_prod(Consumidor.Sref.get_prodRequest request) {
            return base.Channel.get_prod(request);
        }
        
        public string get_prod(int id) {
            Consumidor.Sref.get_prodRequest inValue = new Consumidor.Sref.get_prodRequest();
            inValue.Body = new Consumidor.Sref.get_prodRequestBody();
            inValue.Body.id = id;
            Consumidor.Sref.get_prodResponse retVal = ((Consumidor.Sref.WebService1Soap)(this)).get_prod(inValue);
            return retVal.Body.get_prodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Sref.get_prodResponse> Consumidor.Sref.WebService1Soap.get_prodAsync(Consumidor.Sref.get_prodRequest request) {
            return base.Channel.get_prodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Sref.get_prodResponse> get_prodAsync(int id) {
            Consumidor.Sref.get_prodRequest inValue = new Consumidor.Sref.get_prodRequest();
            inValue.Body = new Consumidor.Sref.get_prodRequestBody();
            inValue.Body.id = id;
            return ((Consumidor.Sref.WebService1Soap)(this)).get_prodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Sref.get_all_prodResponse Consumidor.Sref.WebService1Soap.get_all_prod(Consumidor.Sref.get_all_prodRequest request) {
            return base.Channel.get_all_prod(request);
        }
        
        public string get_all_prod() {
            Consumidor.Sref.get_all_prodRequest inValue = new Consumidor.Sref.get_all_prodRequest();
            inValue.Body = new Consumidor.Sref.get_all_prodRequestBody();
            Consumidor.Sref.get_all_prodResponse retVal = ((Consumidor.Sref.WebService1Soap)(this)).get_all_prod(inValue);
            return retVal.Body.get_all_prodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Sref.get_all_prodResponse> Consumidor.Sref.WebService1Soap.get_all_prodAsync(Consumidor.Sref.get_all_prodRequest request) {
            return base.Channel.get_all_prodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Sref.get_all_prodResponse> get_all_prodAsync() {
            Consumidor.Sref.get_all_prodRequest inValue = new Consumidor.Sref.get_all_prodRequest();
            inValue.Body = new Consumidor.Sref.get_all_prodRequestBody();
            return ((Consumidor.Sref.WebService1Soap)(this)).get_all_prodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Sref.update_prodResponse Consumidor.Sref.WebService1Soap.update_prod(Consumidor.Sref.update_prodRequest request) {
            return base.Channel.update_prod(request);
        }
        
        public string update_prod(int id, string cod, string nombre, string marca, string desc, double compra, double venta, string material) {
            Consumidor.Sref.update_prodRequest inValue = new Consumidor.Sref.update_prodRequest();
            inValue.Body = new Consumidor.Sref.update_prodRequestBody();
            inValue.Body.id = id;
            inValue.Body.cod = cod;
            inValue.Body.nombre = nombre;
            inValue.Body.marca = marca;
            inValue.Body.desc = desc;
            inValue.Body.compra = compra;
            inValue.Body.venta = venta;
            inValue.Body.material = material;
            Consumidor.Sref.update_prodResponse retVal = ((Consumidor.Sref.WebService1Soap)(this)).update_prod(inValue);
            return retVal.Body.update_prodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Sref.update_prodResponse> Consumidor.Sref.WebService1Soap.update_prodAsync(Consumidor.Sref.update_prodRequest request) {
            return base.Channel.update_prodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Sref.update_prodResponse> update_prodAsync(int id, string cod, string nombre, string marca, string desc, double compra, double venta, string material) {
            Consumidor.Sref.update_prodRequest inValue = new Consumidor.Sref.update_prodRequest();
            inValue.Body = new Consumidor.Sref.update_prodRequestBody();
            inValue.Body.id = id;
            inValue.Body.cod = cod;
            inValue.Body.nombre = nombre;
            inValue.Body.marca = marca;
            inValue.Body.desc = desc;
            inValue.Body.compra = compra;
            inValue.Body.venta = venta;
            inValue.Body.material = material;
            return ((Consumidor.Sref.WebService1Soap)(this)).update_prodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Sref.delete_prodResponse Consumidor.Sref.WebService1Soap.delete_prod(Consumidor.Sref.delete_prodRequest request) {
            return base.Channel.delete_prod(request);
        }
        
        public string delete_prod(int id) {
            Consumidor.Sref.delete_prodRequest inValue = new Consumidor.Sref.delete_prodRequest();
            inValue.Body = new Consumidor.Sref.delete_prodRequestBody();
            inValue.Body.id = id;
            Consumidor.Sref.delete_prodResponse retVal = ((Consumidor.Sref.WebService1Soap)(this)).delete_prod(inValue);
            return retVal.Body.delete_prodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Sref.delete_prodResponse> Consumidor.Sref.WebService1Soap.delete_prodAsync(Consumidor.Sref.delete_prodRequest request) {
            return base.Channel.delete_prodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Sref.delete_prodResponse> delete_prodAsync(int id) {
            Consumidor.Sref.delete_prodRequest inValue = new Consumidor.Sref.delete_prodRequest();
            inValue.Body = new Consumidor.Sref.delete_prodRequestBody();
            inValue.Body.id = id;
            return ((Consumidor.Sref.WebService1Soap)(this)).delete_prodAsync(inValue);
        }
    }
}
